--OPERAZIONI_BASE CORSISTA
SELECT CORSISTA.COD_CORSISTA,CORSISTA.NOME_CORSISTA,CORSISTA.COGNOME_CORSITA,CORSISTA.PRECEDENTI_FORMATIVI 

FROM CORSISTA; -- PER INSERT E GET ALL

SELECT CORSISTA.*
FROM CORSISTA
WHERE COD_CORSISTA = ?

--END OPERAZIONE CORSISTA


--OPERAZIONI_BASE CORSISTA
SELECT CORSO.COD_CORSO,CORSO.NOME_CORSO,CORSO.DATA_INIZIO,CORSO.DATA_FINE,CORSO.COSTO_CORSO,CORSO.COMMENTI_CORSO,CORSO.AULA_CORSO,CORSO.COD_DOCENTE
FROM CORSO; --PER INSERT E GET ALL

SELECT CORSO.*
FROM CORSO
WHERE COD_CORSO = ? 

SELECT CORSO.*
FROM CORSO 
WHERE COD_DOCENTE = ?
--END OPERAZIONE CORSO



--STATISTICHE
--1
SELECT COUNT(*)
FROM CORSISTA
--END 1
--2
SELECT COD_CORSO,COUNT(COD_CORSISTA) 
FROM CORSO_CORSITA
GROUP BY COD_CORSO
HAVING COUNT(COD_CORSISTA)  = 12
--END 2
--3
SELECT CORSO.*
FROM CORSO
WHERE DATA_INIZIO = (SELECT MAX(DATA_INIZIO)
                     FROM CORSO)
--END 3
--4

--END 4

--5
CREATE VIEW CORSO_COMMENTI AS 
SELECT DISTINCT COD_CORSO,regexp_substr(CORSO.commenti_corso, '[^;]+', 1, LEVEL) COMMENTI
FROM CORSO
CONNECT BY regexp_substr(CORSO.commenti_corso, '[^;]+', 1, LEVEL) IS NOT NULL;

SELECT COD_CORSO, COUNT(COMMENTI) 
FROM CORSO_COMMENTI
GROUP BY COD_CORSO
;

--END 5

--6
--UGUALE AL GET ALL
--END 

--7
CREATE VIEW DOCENTE_CV AS 
SELECT DISTINCT COD_DOCENTE,regexp_substr(DOCENTE.CV, '[^;]+', 1, LEVEL) MATERIE
FROM DOCENTE
CONNECT BY regexp_substr(DOCENTE.CV, '[^;]+', 1, LEVEL) IS NOT NULL;

SELECT COD_DOCENTE, COUNT(MATERIE) 
FROM DOCENTE_CV
GROUP BY COD_DOCENTE
HAVING COUNT(MATERIE) = (SELECT MAX(COUNT(MATERIE))
                        FROM DOCENTE_CV
                        GROUP BY COD_DOCENTE
                        
                        )
;
--END 7

--8
SELECT COD_CORSO,COUNT(COD_CORSISTA)
FROM CORSO_CORSITA CC
GROUP BY(COD_CORSO)
HAVING COUNT(COD_CORSISTA) = (SELECT MIN(COUNT(COD_CORSISTA)
                              FROM CORSO_CORSISTA
                              CC.COD_CORSO = CORSO_CORSISTA.COD_CORSO           
                            )
--END 8
                     
---END STATISTICHE